version: "3.8"

services:
  app:
    image: zidio-app                        # Your Spring Boot app image
    container_name: zidio-container
    ports:
      - "9090:8889"                         # Host 9090 → Container 8889 (Spring Boot port)
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-container:3306/zidio_connection?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Yamini9573
      - SPRING_REDIS_HOST=redis-container
      - SPRING_REDIS_PORT=6379
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  mysql:
    image: mysql:8
    container_name: mysql-container
    environment:
      - MYSQL_ROOT_PASSWORD=Yamini9573
      - MYSQL_DATABASE=zidio_connection
    ports:
      - "3307:3306"                          # Host 3307 → Container 3306 (MySQL)
    volumes:
      - mysql_data:/var/lib/mysql            # Persistent MySQL data
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pYamini9573"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: redis-container
    ports:
      - "6379:6379"                          # Expose Redis
    volumes:
      - redis_data:/data                     # Persistent Redis data
    command: ["redis-server", "--appendonly", "yes"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    restart: unless-stopped

volumes:
  mysql_data:                               # Persistent MySQL volume
    external: true                           # Ensure it exists: docker volume create mysql_data
  redis_data:                                # Persistent Redis volume
